# Generated by Django 3.0.3 on 2020-02-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Households',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hshd_id', models.IntegerField()),
                ('loyalty', models.BooleanField()),
                ('age_range', models.CharField(max_length=20)),
                ('marital_status', models.CharField(max_length=10)),
                ('income_range', models.CharField(max_length=15)),
                ('homeowner', models.CharField(max_length=10)),
                ('hshd_comp', models.CharField(max_length=20)),
                ('hh_size', models.CharField(max_length=3)),
                ('children', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hshd_id', models.IntegerField()),
                ('bskt_id', models.IntegerField()),
                ('trans_date', models.DateField()),
                ('product_id', models.IntegerField()),
                ('spend', models.FloatField()),
                ('units', models.IntegerField()),
                ('store_region', models.CharField(max_length=10)),
                ('week_num', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
