# Generated by Django 3.0.3 on 2020-02-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20200223_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='hshd_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
